### ISSUE TITLE
#ifhave and #ifnhave preprocessor directive is missing

### ISSUE THREAD

**Issue by Psimage** [Byteron/wml#2]
![image](https://user-images.githubusercontent.com/787038/38558174-ff868096-3cd7-11e8-9206-ae7cb1f2a97f.png)

https://wiki.wesnoth.org/PreprocessorRef#.23ifhave_and_.23ifnhave

**Comment by Byteron** [comment]
Ah, thanks. Fixed in 1.0.5. :)
